services:
  db:
    image: postgres:15-alpine
    container_name: postgres
    volumes:
      - ./db/create_database.sql:/docker-entrypoint-initdb.d/create_database.sql
        - ./db/init_tasks.sql:/docker-entrypoint-initdb.d/init_tasks.sql
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"

  web:
    build:
      context: ./web
    container_name: php-fpm-nginx
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
